# Generated by Django 2.0.5 on 2019-08-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_details', '0002_auto_20190802_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('ifsc', models.CharField(db_column='ifsc', max_length=11, primary_key=True, serialize=False)),
                ('bank_id', models.IntegerField(db_column='bank_id', primary_key=True)),
                ('branch', models.CharField(db_column='branch', max_length=74, primary_key=True)),
                ('address', models.CharField(db_column='address', max_length=195, primary_key=True)),
                ('city', models.CharField(db_column='city', max_length=50, primary_key=True)),
                ('district', models.CharField(db_column='district', max_length=50, primary_key=True)),
                ('state', models.CharField(db_column='state', max_length=26, primary_key=True)),
                ('bank_name', models.CharField(db_column='bank_name', max_length=49)),
            ],
            options={
                'db_table': 'bank_branches',
            },
        ),
    ]
